import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.PriorityQueue;
import java.util.UUID;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

/**
 * Project 2: Simple HFT-Style Limit Order Book & Matching Engine.
 *
 * HFT concept:
 * - All modern electronic exchanges use an order book.
 *   * BUY orders (bids) sorted from highest to lowest price.
 *   * SELL orders (asks) sorted from lowest to highest price.
 * - When a new order arrives, it is matched against the opposite side of the book.
 *
 * This example:
 * - Shows how a small in-memory matching engine works.
 * - Uses a ReentrantLock to simulate thread-safe matching (one matching operation at a time).
 */
public class SimpleLimitOrderBook {

    enum Side { BUY, SELL }

    enum OrderType { LIMIT }

    /**
     * Represents one limit order.
     */
    static class Order {
        final String orderId;
        final String symbol;
        final Side side;
        final OrderType type;
        final double price;
        long quantity;   // remaining quantity that is not yet filled
        final Instant createdTime;

        Order(String symbol, Side side, double price, long quantity) {
            this.orderId = UUID.randomUUID().toString();
            this.symbol = symbol;
            this.side = side;
            this.type = OrderType.LIMIT;
            this.price = price;
            this.quantity = quantity;
            this.createdTime = Instant.now();
        }

        @Override
        public String toString() {
            return "Order{" +
                    "orderId='" + orderId + '\'' +
                    ", symbol='" + symbol + '\'' +
                    ", side=" + side +
                    ", price=" + price +
                    ", quantity=" + quantity +
                    ", createdTime=" + createdTime +
                    '}';
        }
    }

    /**
     * Represents a trade result when two orders match.
     */
    static class Trade {
        final String buyOrderId;
        final String sellOrderId;
        final String symbol;
        final double price;
        final long quantity;
        final Instant tradeTime;

        Trade(String buyOrderId, String sellOrderId, String symbol, double price, long quantity) {
            this.buyOrderId = buyOrderId;
            this.sellOrderId = sellOrderId;
            this.symbol = symbol;
            this.price = price;
            this.quantity = quantity;
            this.tradeTime = Instant.now();
        }

        @Override
        public String toString() {
            return "Trade{" +
                    "buyOrderId='" + buyOrderId + '\'' +
                    ", sellOrderId='" + sellOrderId + '\'' +
                    ", symbol='" + symbol + '\'' +
                    ", price=" + price +
                    ", quantity=" + quantity +
                    ", tradeTime=" + tradeTime +
                    '}';
        }
    }

    /**
     * A basic limit order book for a single symbol.
     * - buyBook: highest price first, then earliest time
     * - sellBook: lowest price first, then earliest time
     * We protect matching with a lock so multiple threads could safely call submitOrder.
     */
    static class OrderBook {
        private final String symbol;

        // BUY: highest price first (max-heap behavior via reversed comparator)
        private final PriorityQueue<Order> buyBook = new PriorityQueue<>(
                Comparator.<Order>comparingDouble(o -> -o.price) // negative for descending price
                        .thenComparing(o -> o.createdTime)
        );

        // SELL: lowest price first
        private final PriorityQueue<Order> sellBook = new PriorityQueue<>(
                Comparator.<Order>comparingDouble(o -> o.price)
                        .thenComparing(o -> o.createdTime)
        );

        private final Lock lock = new ReentrantLock();

        OrderBook(String symbol) {
            this.symbol = symbol;
        }

        /**
         * Submit a new LIMIT order into the book.
         *
         * @return list of trades generated by this order (could be empty if no match).
         */
        public List<Trade> submitOrder(Order incoming) {
            lock.lock();
            try {
                if (!incoming.symbol.equals(symbol)) {
                    throw new IllegalArgumentException("Order symbol " + incoming.symbol +
                            " does not match book symbol " + symbol);
                }

                List<Trade> trades = new ArrayList<>();

                if (incoming.side == Side.BUY) {
                    matchBuy(incoming, trades);
                    // If still remaining volume, add to book
                    if (incoming.quantity > 0) {
                        buyBook.add(incoming);
                    }
                } else {
                    matchSell(incoming, trades);
                    if (incoming.quantity > 0) {
                        sellBook.add(incoming);
                    }
                }

                return trades;
            } finally {
                lock.unlock();
            }
        }

        /**
         * Match an incoming BUY order against the best SELL orders.
         */
        private void matchBuy(Order buy, List<Trade> trades) {
            while (buy.quantity > 0 && !sellBook.isEmpty()) {
                Order bestAsk = sellBook.peek();
                // If best SELL price is greater than BUY price, no match
                if (bestAsk.price > buy.price) {
                    break;
                }

                long tradedQty = Math.min(buy.quantity, bestAsk.quantity);
                double tradePrice = bestAsk.price; // price usually at order in the book (maker price)

                buy.quantity -= tradedQty;
                bestAsk.quantity -= tradedQty;

                trades.add(new Trade(
                        buy.orderId,
                        bestAsk.orderId,
                        buy.symbol,
                        tradePrice,
                        tradedQty
                ));

                if (bestAsk.quantity == 0) {
                    // Remove fully filled order from the book
                    sellBook.poll();
                }
            }
        }

        /**
         * Match an incoming SELL order against the best BUY orders.
         */
        private void matchSell(Order sell, List<Trade> trades) {
            while (sell.quantity > 0 && !buyBook.isEmpty()) {
                Order bestBid = buyBook.peek();
                // If best BUY price is less than SELL price, no match
                if (bestBid.price < sell.price) {
                    break;
                }

                long tradedQty = Math.min(sell.quantity, bestBid.quantity);
                double tradePrice = bestBid.price; // price usually at order in the book (maker price)

                sell.quantity -= tradedQty;
                bestBid.quantity -= tradedQty;

                trades.add(new Trade(
                        bestBid.orderId,
                        sell.orderId,
                        sell.symbol,
                        tradePrice,
                        tradedQty
                ));

                if (bestBid.quantity == 0) {
                    buyBook.poll();
                }
            }
        }

        /**
         * Print current state of the order book.
         * This is just for debugging / learning; real systems don't usually print like this.
         */
        public void printOrderBookSnapshot() {
            System.out.println("====== ORDER BOOK SNAPSHOT for " + symbol + " ======");
            System.out.println("--- BUY side (bids) ---");
            buyBook.stream()
                    .sorted(Comparator.<Order>comparingDouble(o -> -o.price)
                            .thenComparing(o -> o.createdTime))
                    .forEach(o -> System.out.println("BUY " + o.quantity + " @ " + o.price));

            System.out.println("--- SELL side (asks) ---");
            sellBook.stream()
                    .sorted(Comparator.<Order>comparingDouble(o -> o.price)
                            .thenComparing(o -> o.createdTime))
                    .forEach(o -> System.out.println("SELL " + o.quantity + " @ " + o.price));

            System.out.println("==============================");
        }
    }

    public static void main(String[] args) {
        // 1. Create an order book for a single symbol.
        OrderBook book = new OrderBook("AAPL");

        // 2. Pre-load book with some "resting" orders, like a real market.
        System.out.println("Adding initial resting orders...");
        book.submitOrder(new Order("AAPL", Side.SELL, 101.5, 100));
        book.submitOrder(new Order("AAPL", Side.SELL, 102.0, 200));
        book.submitOrder(new Order("AAPL", Side.BUY, 99.5, 150));
        book.submitOrder(new Order("AAPL", Side.BUY, 99.0, 100));

        book.printOrderBookSnapshot();

        // 3. Submit an aggressive BUY order that can cross the spread and trade.
        System.out.println("\nSubmitting aggressive BUY order: 250 @ 102.0");
        Order aggressiveBuy = new Order("AAPL", Side.BUY, 102.0, 250);
        List<Trade> trades1 = book.submitOrder(aggressiveBuy);

        System.out.println("Trades generated by aggressive BUY:");
        trades1.forEach(System.out::println);

        book.printOrderBookSnapshot();

        // 4. Submit an aggressive SELL order that trades against the best bids.
        System.out.println("\nSubmitting aggressive SELL order: 180 @ 99.5");
        Order aggressiveSell = new Order("AAPL", Side.SELL, 99.5, 180);
        List<Trade> trades2 = book.submitOrder(aggressiveSell);

        System.out.println("Trades generated by aggressive SELL:");
        trades2.forEach(System.out::println);

        book.printOrderBookSnapshot();

        // 5. You can extend this project by:
        //    - Adding order cancellation
        //    - Supporting multiple symbols (map from symbol to OrderBook)
        //    - Measuring how many orders per second you can process
        //    - Persisting trades to a file or database
    }
}
